services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db_laravel

    db_laravel:
        image: mysql:8.0
        environment:
          MYSQL_DATABASE: db_laravel
          MYSQL_USER: db_user
          MYSQL_PASSWORD: laravel
          MYSQL_ROOT_PASSWORD: laravel
        ports:
            - 3306:3306
